constants:
  CC: gcc
  CFLAGS:
  BIN: "cproj"
  SOURCES: "{{joinlines (shell 'find . -name \"*.c\"')}}"
  BUILDDIR: build
jobs:
  builddir:
    outputs: ["{{BUILDDIR}}"]
    run: mkdir -vp {{BUILDDIR}}

  object:
    args: [path]
    requires:
      - job: builddir
    inputs: ["{{path}}"]
    outputs: ["{{BUILDDIR}}/{{subst path '.c' '.o'}}"]
    run: |
      echo "compiling."
      sleep 1
      echo "compiling.."
      sleep 1
      echo "compiling..."
      sleep 1
      {{CC}} {{CFLAGS}} -c {{path}} -o "{{BUILDDIR}}/{{subst path '.c' '.o'}}"

  binary:
    requires:
      - job: object
        with_list:
          param: path
          inputs: "{{SOURCES}}"
      - job: builddir
    input_list: "{{re SOURCES '([^\\\\s]*).c' (cat BUILDDIR '/' '$1.o')}}"
    output_list: "{{BUILDDIR}}/{{BIN}}"
    run: |
      echo "linking."
      sleep 1
      echo "linking.."
      sleep 1
      echo "linking..."
      sleep 1
      {{CC}} {{CFLAGS}} -o "{{BUILDDIR}}/{{BIN}}" {{re SOURCES '([^\\\\s ]*).c' (cat BUILDDIR '/' '$1.o')}}

  clean:
    run: |
      rm -rf *.o
      rm -rf {{BIN}}

  default:
    requires:
      - job: binary
