constants:
  CC: gcc
  CFLAGS:
  BIN: "cproj"
  SOURCES: "{{joinlines (shell 'find . -name \"*.c\"')}}"
jobs:
  object:
    args: [path]
    inputs: ["{{path}}"]
    outputs: ["{{subst path '.c' '.o'}}"]
    run: |
      echo "compiling."
      sleep 1
      echo "compiling.."
      sleep 1
      echo "compiling..."
      sleep 1
      {{CC}} {{CFLAGS}} -c {{path}}

  binary:
    requires:
      - job: object
        with_list:
          param: path
          inputs: "{{SOURCES}}"
    input_list: "{{subst SOURCES '.c' '.o'}}"
    output_list: "{{BIN}}"
    run: |
      echo "linking."
      sleep 1
      echo "linking.."
      sleep 1
      echo "linking..."
      sleep 1
      {{CC}} {{CFLAGS}} -o {{BIN}} {{subst SOURCES '.c' '.o'}}

  clean:
    run: |
      rm -rf *.o
      rm -rf {{BIN}}

  default:
    requires:
      - job: binary
