name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    strategy:
      matrix:
        features: ["default", ""]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --no-default-features --features "${{ matrix.features }}"
    - name: Run clippy
      run: cargo clippy --all-targets --no-default-features --features "${{ matrix.features }}"
    - name: Run tests
      run: cargo test --verbose --no-default-features --features "${{ matrix.features }}"
    - name: Build release version
      run: cargo build --release --verbose --no-default-features --features "${{ matrix.features }}"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: zinn-${{ matrix.features }}
        path: target/release/zinn
